"use client";

import { ChevronLeft, ChevronRight, Pause, Play } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useEffect, useState } from "react";

type CarouselStage = "study" | "build" | "flight";

export default function RocketReportCarousel({ lang, stage = "study" }: { lang: "fr" | "en"; stage?: CarouselStage }) {
  const fr = lang === "fr";
  const slides = fr ? {
    study: [["carte 2 .jpg", "Intégration interne", "Aménagement du volume embarqué de la microfusée."], ["vue 2.png", "Vue CAO complémentaire", "Vérification de l'intégration des éléments de conception."], ["vue 1.png", "Vue CAO", "Architecture générale de la microfusée ASTRAF."]],
    build: [["vue 1.png", "Vue CAO", "Architecture générale de la microfusée."], ["vue 2.png", "Vue CAO complémentaire", "Vérification de l'intégration des éléments."], ["carte 1.jpg", "Assemblage mécanique", "Décomposition de la fusée et de ses sous-ensembles."], ["carte 2 .jpg", "Intégration interne", "Aménagement du volume embarqué."], ["carte 3 .jpg", "Coiffe et instrumentation", "Intégration de la partie avant."], ["image-1788428649979.png", "Impression 3D de la coiffe", "Préparation de la pièce sous Bambu Studio."], ["image-1788428668529.png", "Impression 3D de l'empennage", "Préparation du gabarit et des ailerons."], ["image-1788428678487.png", "Impression 3D des ailerons", "Contrôle de l'orientation et des supports."], ["carte electr.png", "Carte électronique", "RP2040-Zero, capteurs et alimentation embarqués."], ["nouveau trajecto .png", "Trajectographie", "Analyse de la trajectoire et des phases de vol."], ["nouveau stabilito.png", "Stabilité", "Vérification de la stabilité et du comportement aérodynamique."]],
    flight: [["Figure 2026-05-17 182925 (5).png", "Prototype assemblé", "La microfusée ASTRAF prête pour les essais."], ["pression+altitude.jpg", "Altitude et pression", "Lecture de la phase propulsée, de l'apogée et de la descente."], ["accelerations.png", "Accélérations", "Les trois axes mettent en évidence le départ et les phases de vol."], ["gyroscopes.png", "Vitesses angulaires", "La réponse inertielle permet d'observer la stabilité en vol."], ["temperatures.png", "Température", "Température enregistrée par l'électronique embarquée."]],
  } : {
    study: [["carte 2 .jpg", "Internal integration", "Onboard-volume layout for the micro-rocket."], ["vue 2.png", "Complementary CAD view", "Verification of the design-component integration."], ["vue 1.png", "CAD view", "Overall ASTRAF micro-rocket architecture."]],
    build: [["vue 1.png", "CAD view", "General micro-rocket architecture."], ["vue 2.png", "Complementary CAD view", "Verification of component integration."], ["carte 1.jpg", "Mechanical assembly", "Rocket and subsystem breakdown."], ["carte 2 .jpg", "Internal integration", "Onboard-volume layout."], ["carte 3 .jpg", "Nose cone and instrumentation", "Forward-section integration."], ["image-1788428649979.png", "3D-printed nose cone", "Part preparation in Bambu Studio."], ["image-1788428668529.png", "3D-printed fin assembly", "Jig and fin preparation."], ["image-1788428678487.png", "3D-printed fins", "Orientation and support checking."], ["carte electr.png", "Electronics board", "Onboard RP2040-Zero, sensors, and power supply."], ["nouveau trajecto .png", "Trajectory analysis", "Analysis of trajectory and flight phases."], ["nouveau stabilito.png", "Stability analysis", "Verification of stability and aerodynamic behavior."]],
    flight: [["Figure 2026-05-17 182925 (5).png", "Assembled prototype", "ASTRAF micro-rocket ready for testing."], ["pression+altitude.jpg", "Altitude and pressure", "Reading powered flight, apogee, and descent."], ["accelerations.png", "Accelerations", "The three axes reveal lift-off and flight phases."], ["gyroscopes.png", "Angular velocities", "The inertial response helps observe flight stability."], ["temperatures.png", "Temperature", "Temperature recorded by the onboard electronics."]],
  };
  const selectedSlides = slides[stage];
  const [index, setIndex] = useState(0);
  const [isPaused, setIsPaused] = useState(false);
  useEffect(() => { if (isPaused) return; const interval = window.setInterval(() => setIndex((current) => (current + 1) % selectedSlides.length), 5000); return () => window.clearInterval(interval); }, [isPaused, selectedSlides.length]);
  const [src, label, detail] = selectedSlides[index];
  const move = (direction: 1 | -1) => setIndex((current) => (current + direction + selectedSlides.length) % selectedSlides.length);

  return <figure className="relative overflow-hidden border border-border bg-[#091019] p-2 shadow-2xl"><div className="relative flex aspect-[4/3] items-center justify-center overflow-hidden bg-white"><AnimatePresence mode="wait" initial={false}><motion.img key={src} src={`/Fusée/asset/${src}`} alt={label} initial={{ opacity: 0, scale: 1.02 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }} className="absolute inset-0 size-full object-contain" /></AnimatePresence></div><figcaption className="flex min-h-16 items-center justify-between gap-4 px-3 py-3 font-mono text-[10px] uppercase tracking-wide text-text-dim"><div><p className="text-metal-light">{label}</p><p className="mt-1 text-[9px] text-text-faint">{detail}</p></div><div className="flex gap-1"><button type="button" onClick={() => move(-1)} className="inline-flex size-8 items-center justify-center border border-border transition hover:border-metal hover:text-white" aria-label={fr ? "Image précédente" : "Previous image"}><ChevronLeft className="size-4" /></button><button type="button" onClick={() => setIsPaused((paused) => !paused)} className="inline-flex size-8 items-center justify-center border border-border transition hover:border-metal hover:text-white" aria-label={isPaused ? (fr ? "Lire le carrousel" : "Play carousel") : (fr ? "Mettre le carrousel en pause" : "Pause carousel")}>{isPaused ? <Play className="size-3.5" /> : <Pause className="size-3.5" />}</button><button type="button" onClick={() => move(1)} className="inline-flex size-8 items-center justify-center border border-border transition hover:border-metal hover:text-white" aria-label={fr ? "Image suivante" : "Next image"}><ChevronRight className="size-4" /></button></div></figcaption><div className="absolute left-5 top-5 flex gap-1.5" aria-hidden="true">{selectedSlides.map(([slideSrc], slideIndex) => <span key={slideSrc} className={`h-1 w-5 ${slideIndex === index ? "bg-accent" : "bg-slate-700/50"}`} />)}</div></figure>;
}